services:
  zookeeper:
    image: zookeeper:3.8 
    container_name: zookeeper_standalone
    restart: always
    ports:
      - "2181:2181" 
    volumes:
      - ./data:/data        
      - ./datalog:/datalog  
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
